In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('airport_route_survey.csv')

In [3]:
df.columns

Index(['respondent_id', 'origin', 'route'], dtype='object')

In [6]:
df.sample(6)

     respondent_id                  origin  route
150            151              Transplant  South
219            220              Transplant  South
197            198  Greater Madison native  North
118            119  Greater Madison native  South
107            108          Madison native  South
14              15              Transplant  South

In [5]:
pd.crosstab(df['origin'], df['route'])

route                   Isthmus  North  South
origin
Greater Madison native       12      9     51
Madison native               62     18     31
Transplant                   33     13     71

In [8]:
data = [
    [12, 9, 51],    # Greater Madison Natives
    [62, 18, 31],   # Madison Natives
    [33, 13, 71]]   # Transplants

In [9]:
data

[[12, 9, 51], [62, 18, 31], [33, 13, 71]]

In [12]:
print(data[0][1]) # Lowest
print(data[2][2]) # Highest

9
71

In [27]:
def summarize_grid(m, verbose=False):
    """Calculates summary statistics for a two-dimensional list of numbers.

    Analyzes a list of sublists containing numbers and calculates overall cell 
    count, total sum, average, and row/column coordinates for the maximum 
    and minimum values.

    Args:
        m (list): A list of lists containing numerical values (ints or floats).

    Returns:
        dict: A dictionary containing summary statistics with the following keys:
            - 'total_cells' (int): Total count of elements across all sublists.
            - 'sum_of_cells' (int or float): Total sum of all numerical values.
            - 'average_of_cells' (float): Arithmetic average of all values.
            - 'max_index' (tuple): Coordinates (row, column) of the largest value.
            - 'min_index' (tuple): Coordinates (row, column) of the smallest value.
    """

    # Create the empty dictionary to populate and send back

    ret_dict = {
        'total_cells': 0,
        'sum_of_cells': 0,
        'max_value': m[0][0],
        'min_value': m[0][0],
        'max_index': (0, 0),
        'min_index': (0, 0),
        'avgerage_of_cells':0}

    for row in range(len(m)):
        for col in range(len(m[row])):
            # print(f"{m[row][col]} - ")
            ret_dict['total_cells'] += 1
            ret_dict['sum_of_cells'] += m[row][col]
            if m[row][col] > ret_dict['max_value']:
                ret_dict['max_value'] = m[row][col]
                ret_dict['max_index'] = (row, col)
            if m[row][col] < ret_dict['min_value']:
                ret_dict['min_value'] = m[row][col]
                ret_dict['min_index'] = (row, col)

    ret_dict['avgerage_of_cells'] = \
        ret_dict['sum_of_cells'] / ret_dict['total_cells']

    if verbose:
        print(ret_dict)
    
    return ret_dict
            

my_summary = summarize_grid(data, verbose=True)
my_summary

{'total_cells': 9, 'sum_of_cells': 300, 'max_value': 71, 'min_value': 9, 'max_index': (2, 2), 'min_index': (0, 1), 'avgerage_of_cells': 33.333333333333336}

{'total_cells': 9,
 'sum_of_cells': 300,
 'max_value': 71,
 'min_value': 9,
 'max_index': (2, 2),
 'min_index': (0, 1),
 'avgerage_of_cells': 33.333333333333336}

In [29]:
def summarize_grid(m, verbose=False):
    """Calculates summary statistics for a two-dimensional list of numbers.

    Analyzes a list of sublists containing numbers and calculates overall cell 
    count, total sum, average, and row/column coordinates for the maximum 
    and minimum values.

    Args:
        m (list): A list of lists containing numerical values (ints or floats).

    Returns:
        dict: A dictionary containing summary statistics with the following keys:
            - 'total_cells' (int): Total count of elements across all sublists.
            - 'sum_of_cells' (int or float): Total sum of all numerical values.
            - 'average_of_cells' (float): Arithmetic average of all values.
            - 'max_index' (tuple): Coordinates (row, column) of the largest value.
            - 'min_index' (tuple): Coordinates (row, column) of the smallest value.
    """

    # Create the empty dictionary to populate and send back

    ret_dict = {
        'total_cells': 0,
        'sum_of_cells': 0,
        'max_value': m[0][0],
        'min_value': m[0][0],
        # 'max_index': (0, 0),
        # 'min_index': (0, 0),
        'avgerage_of_cells':0}

    for row in m:
        for cell in row:
            ret_dict['total_cells'] += 1
            ret_dict['sum_of_cells'] += cell
            if cell > ret_dict['max_value']:
                ret_dict['max_value'] = cell
            if cell < ret_dict['min_value']:
                ret_dict['min_value'] = cell

    ret_dict['avgerage_of_cells'] = \
        ret_dict['sum_of_cells'] / ret_dict['total_cells']

    if verbose:
        print(ret_dict)
    
    return ret_dict
            

my_summary = summarize_grid(data, verbose=True)
my_summary

{'total_cells': 9, 'sum_of_cells': 300, 'max_value': 71, 'min_value': 9, 'avgerage_of_cells': 33.333333333333336}

{'total_cells': 9,
 'sum_of_cells': 300,
 'max_value': 71,
 'min_value': 9,
 'avgerage_of_cells': 33.333333333333336}